### ISSUE TITLE
Issue with Hotel_Sentiment.items

### ISSUE THREAD

**Issue by cgayner** [monkeylearn/hotel-review-analysis#3]
Hi Guys,
I am getting the below issue when I run the tripadvisor_spider.py in Idle 2.7

Traceback (most recent call last):
  File ".../Python/Programs/hotel-review-analysis-master/hotel_sentiment/spiders/tripadvisor_spider.py", line 2, in <module>
    from hotel_sentiment.items import HotelSentimentItem
ImportError: No module named hotel_sentiment.items

Am sure I am doing something wrong, any ideas?

**Comment by cgayner** [comment]
Quick update, I ran the same code in 3.6 (as wasnt sure if the Line 2 code was for 3.6) and got this error:

Traceback (most recent call last):
  File ".../Python/Programs/hotel-review-analysis-master/hotel_sentiment/spiders/tripadvisor_spider.py", line 1, in <module>
    import scrapy
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/http/request/form.py", line 9, in <module>
    import lxml.html
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/etree.so, 2): Symbol not found: _PyBaseString_Type
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/etree.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/etree.so

**Comment by brusteca** [comment]
How are you running it? Running `scrapy crawl tripadvisor -o itemsTripadvisor.csv` like it says in the readme works for me.

As for python 3, the project is written in python 2.7 so python 3 isn't supported

Cheers!

**Comment by cgayner** [comment]
The initial error was a simple one, the folder structure was not right + the URL format in the main folder was wrong used " " when it should have been ' ' 

Fixed it now and seems to be working for me.

**Comment by brusteca** [comment]
👌
